// Generates /sitemap.xml at build time. Crawlers find it via robots.txt
// (which references it explicitly) and via the GSC "Sitemaps" submission.
//
// Notes:
//   • lastModified must be a Date or ISO string — Next encodes it to W3C
//     datetime in the XML.
//   • priority is informational; Google now mostly ignores it, but keeping
//     it sane (1.0 home > 0.8 case studies) helps Bing.
//   • If new routes are added later (e.g. a /writing or /uses page), add
//     entries here — the sitemap is not generated by crawling, it's a list.

import { projects } from "../lib/projects";

const BASE = process.env.NEXT_PUBLIC_BASE_URL;

export default function sitemap() {
  const now = new Date();

  return [
    {
      url: `${BASE}/`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 1,
    },
    ...projects.map((p) => ({
      url: `${BASE}/work/${p.slug}`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.8,
    })),
  ];
}
